package com.mapofzones.commandexecutor;

import java.util.ArrayList;

public interface Constants {
    ArrayList<String> watchersLabels = new ArrayList<>() {{
        add("akashnet-watcher-app");
//        add("alteredcarbon-watcher-app");
        add("assetmantle-watcher-app");
        add("axelar-watcher-app");
        add("band-watcher-app");
        add("bitcanna-watcher-app");
        add("bitsong-watcher-app");
        add("certik-watcher-app");
        add("cheqd-watcher-app");
        add("chihuahua-watcher-app");
        add("comdex-watcher-app");
        add("cosmoshub-watcher-app");
        add("crescent-watcher-app");
        add("cronos-watcher-app");
        add("crypto-org-watcher-app");
        add("cyber-watcher-app");
        add("decentr-watcher-app");
        add("desmos-watcher-app");
        add("dig-watcher-app");
        add("emoney-watcher-app");
        add("evmos-watcher-app");
        add("fetchai-watcher-app");
        add("gravitybridge-watcher-app");
        add("impacthub-watcher-app");
//        add("injectivecleared-watcher-app");
        add("injective-watcher-app");
        add("irishub-watcher-app");
        add("juno-watcher-app");
        add("kava-watcher-app");
//        add("kichainlogged-watcher-app");
        add("kichain-watcher-app");
        add("konstellation-watcher-app");
        add("kujira-watcher-app");
        add("likecoin-watcher-app");
        add("lum-watcher-app");
        add("microtick-watcher-app");
        add("omniflix-watcher-app");
        add("osmosis-watcher-app");
        add("panacea-watcher-app");
        add("persistence-watcher-app");
        add("regen-watcher-app");
        add("rizon-watcher-app");
        add("secret-watcher-app");
        add("sentinel-watcher-app");
        add("sifchain-watcher-app");
        add("sommelier-watcher-app");
        add("stargaze-watcher-app");
        add("starname-watcher-app");
        add("terra-watcher-app");
        add("umee-watcher-app");
        add("vidulum-watcher-app");
        add("functionx-watcher-app");
    }};
}
